### ISSUE TITLE
marshmallow.exceptions.ValidationError: {'sparkhome': ['%s is not a directory']}

### ISSUE THREAD

**Issue by zikai1** [AllenInstitute/BigFeta#26]
Hi [RussTorres](https://github.com/RussTorres),
When I  try to generate 3D point matches using `python -m asap.pointmatch.create_tilepairs` in ASAP as suggested by [https://asap-modules.readthedocs.io/en/latest/readme/rough_alignment.html#step-3-generate-point-matches](url), the following issue arises:
```
Traceback (most recent call last):
  File "/home/asap/render-ws-java-client/asap-modules/asap/pointmatch/generate_point_matches_spark.py", line 154, in <module>
    module = PointMatchClientModuleSpark(input_data=example)
  File "/usr/local/lib/python3.8/dist-packages/argschema/argschema_parser.py", line 175, in __init__
    result = self.load_schema_with_defaults(self.schema, args)
  File "/usr/local/lib/python3.8/dist-packages/argschema/argschema_parser.py", line 274, in load_schema_with_defaults
    result = utils.load(schema, args)
  File "/usr/local/lib/python3.8/dist-packages/argschema/utils.py", line 422, in load
    raise mm.ValidationError(errors)
marshmallow.exceptions.ValidationError: {'sparkhome': ['%s is not a directory']}
```
I use the default `sparkhome` setting in my file: 
`"sparkhome": "/allen/programs/celltypes/workgroups/em-connectomics/ImageProcessing/utils/spark/",`
since I have no idea where to get the `spark directory`. 

The whole settings in my file are:
```
example = {
    "render": {
        "host": "10.8.204.10",
        "port": 9001,
        "owner": "EM_group1",
        "project": "lens_corr1",
        "client_scripts": "/home/asap/render-ws-java-client/src/main/scripts"
    },
    "sparkhome": "/allen/programs/celltypes/workgroups/em-connectomics/ImageProcessing/utils/spark/",
    "masterUrl": "spark://10.8.204.10:7077",
    "logdir": "/home/asap/example_output/", 
    "jarfile": "/home/asap/render-ws-java-client/target/render-ws-spark-client-4.0.0-standalone.jar",
    "className": "org.janelia.render.client.spark.SIFTPointMatchClient",
    "baseDataUrl": "http://10.8.204.10:9001/render-ws/v1",
    "owner": "EM_group1",
    "collection": "mm2_rough_align_test",
    "pairJson": "/home/asap/montageTilepairs3D/tile_pairs_python_montage_results_z_100_to_100_dist_0.json",
    "SIFTfdSize": 8,
    "SIFTsteps": 3,
    "matchMaxEpsilon": 20.0,
    "maxFeatureCacheGb": 15,
    "SIFTminScale": 0.38,
    "SIFTmaxScale": 0.82,
    "renderScale": 0.3,
    "matchRod": 0.9,
    "matchMinInlierRatio": 0.0,
    "matchMinNumInliers": 8,
    "matchMaxNumInliers": 200
}
```

Hi [RussTorres](https://github.com/RussTorres), could you tell me how can I attain the correct `spark directory`? Thank you very much for your help! Thanks~

Best wishes,
MY

**Comment by RussTorres** [comment]
There should be some usage hints or descriptions when you use `--help` on the command line.  Some of these are more useful than others.  For sparkhome, it reads:
`"Spark home directory containing bin/spark_submit"`

So I believe this should be wherever you installed spark (though it looks like you are using an existing spark cluster, so maybe you need to find where the supporting files are or install them locally).  For prototyping I also like to use the `local[<num_procs>,<num_retries>]` parameter for `masterUrl` to keep everything local.

Best,
Russel

**Comment by zikai1** [comment]
> 

Thank you for your help, RussTorres. I will try to install spark in local.
