### ISSUE TITLE
When there is no metafile, how to import the images to render-ws

### ISSUE THREAD

**Issue by zikai1** [AllenInstitute/BigFeta#27]
Hi Russel Torres,
 Sorry for disturbing you.

  I currently perform the EM stitching and alignment based on` ASAP-modules`. Typically, in the first step of ASAP, I need to conduct `python -m asap.mesh_lens_correction.do_mesh_lens_correction` and the camera info is stored in `metafile` as shown in the `example` [https://github.com/AllenInstitute/asap-modules/blob/master/asap/mesh_lens_correction/do_mesh_lens_correction.py](url). 

The snapshot of a metafile example provided by you is
![7e18f475b3444b2960dd826fe01ca51](https://user-images.githubusercontent.com/37583980/225238662-d65993d2-6d59-46e3-9251-424417edb2eb.png)

However, how to directly import  EM images to the render without setting the metafile, since I only have EM images without camera info. The snapshort of my images is
![4db750dea35808c2b603b2256c7412d](https://user-images.githubusercontent.com/37583980/225239224-6e5bddc9-b3d8-4e87-b35d-a6174cc423ef.png)

Hi Russel Torres, is there any method to solve the above problem? Thanks a lot for your help. Thank you!

Best,
MY

**Comment by RussTorres** [comment]
First, these images do not appear to be sufficiently overlapping to do lens correction.  We really recommend acquiring images in at least a 3x3 array that overlap by at least 50% (optimal is some distribution  of overlaps between 50% and 60%) with their up/down and left/right neighbors to compensate for the distortion inherent in the lens system.  This is what `do_mesh_lens_correction` tries to do.
Despite that, these should define a montage that can be stitched using the montage solver (or bigfeta directly as described in em-stitch).  If the overlap is known, you can create tilespecs like this:


```python
# NOTE: code written without access to input data -- may have errors

import dataclasses
import pathlib

import renderapi


def removeprefix(s, prefix):
    try:
        # python 3.9+ has this
        return s.removeprefix(prefix)
    except AttributeError:
        if s.startswith(prefix):
            return s[len(prefix):]
        return s


@dataclasses.dataclass
class MontageImage:
    """helper class for handling montage image metadata"""
    img_path : pathlib.Path
    layer_int : int
    row_int : int
    column_int : int
    
    @classmethod
    def from_fname(cls, fname):
        img_path = pathlib.Path(fname)
        stem = img_path.stem
        lstr, rstr, cstr = stem.split("_")
        layer_int = int(removeprefix(lstr, "layer"))
        row_int = int(rstr)
        column_int = int(cstr)
        return MontageImage(
            img_path, layer_int, row_int, column_int)
    
    def get_position(
            self, width, height,
            overlap_factor_column,
            overlap_factor_row):
        x = width * self.column_int * (1 - overlap_factor_column)
        y = height * self.row_int * (1 - overlap_factor_row)
        return x, y
    
    def get_tilespec(
            self, width, height,
            overlap_factor_column,
            overlap_factor_row):
        xy_pos = self.get_position(width, height, overlap_factor_column, overlap_factor_row)
        tform = renderapi.transform.TranslationModel(
            B0=xy_pos[0], B1=xy_pos[0])
        
        ip = renderapi.image_pyramid.ImagePyramid()
        ip[0] = renderapi.image_pyramid.MipMap(
            imageUrl=self.img_path.absolute().as_uri())
        
        tspec = renderapi.tilespec.TileSpec(
            tileId=self.img_path.stem,
            sectionId=str(self.layer_int),
            tforms=[tform],
            imagePyramid=ip,
            width=width,
            height=height,
            z=self.layer_int
        )
        return tspec

# change these to match your values!
overlap_factor_row = 0.1
overlap_factor_column = 0.1
width = 1000
height = 1000

     
montage_images = [MontageImage.from_fname(fname) for fname in fnames]
tspecs = [
    montage_image.get_tilespec(
        width, height, overlap_factor_column, overlap_factor_row)
    for montage_image in montage_images]
```

Then you can do something like this to add the tilespecs to a render stack:

```python

# fill this in
render_connect = {
   "owner": "test_user",
    "project": "test_projects",
    "port": 8888,
    "host": "myhost",
    "client_scripts": ""
}
r = renderapi.connect(**render_connect)

montage_stack = "some_test_stack"

renderapi.stack.create_stack(montage_stack, render=r)
renderapi.resolvedtiles.put_tilespecs(montage_stack, tilespecs=tspecs, render=r)
renderapi.stack.set_stack_state(montage_stack, "COMPLETE", render=r)
```

This is essentially what `asap.dataimport.generate_EM_tilespecs_from_metafile` does, but based on our custom metadata format (which incorporates information from the microscope stage).  For a pipeline use case I'd suggest developing a metadata format that either matches our expectation or subclass that module to work for your version.

**Comment by zikai1** [comment]
@RussTorres  Thank you very much Russ Torres! You are the best developer that I met. 

I will take your suggestions in my data.

Best wishes,
MY

**Comment by zikai1** [comment]
I have successfully loaded my images in a render stack by customizing these data in your provided metadata file. 

Thanks for your help, Russ Torres.
