### ISSUE TITLE
Are these stitching results correct?

### ISSUE THREAD

**Issue by zikai1** [AllenInstitute/BigFeta#28]
Hi Russel Torres,
The following image is a 2D stitching result following the `asap-modules` [https://asap-modules.readthedocs.io/en/latest/index.html](asap-modules). 
![1679491249389](https://user-images.githubusercontent.com/37583980/226917239-5856d0a4-0c20-490c-abdf-a501d203096e.png)
The metadata I test is `21617_R1_166_T5_15_20201231140731_20201231140731` provided by you. Followings are visualization error maps with a html format:

![1679491354556](https://user-images.githubusercontent.com/37583980/226917720-1121edb3-32b6-4f98-9d0b-bc127062d66d.png)
![1278ff883ad54f41a2203b3f9c3e137](https://user-images.githubusercontent.com/37583980/226917887-10bb3dd2-8856-4927-9342-0b8797f505c4.png)
![23d33b5804cf8859b5af08835bcd0ce](https://user-images.githubusercontent.com/37583980/226917976-5aec3d44-8f23-46b7-a357-390028e08378.png)

Are these stitching results correct? Why do they look like undergoing a spatial rotation? In addition, I also test some EM tiles sampled by ourselves, the 2D stitching results are also rotated by some degree. How do I solve the above problem? 

Thanks in advance, Russel Torres. Thank you!

Best and sincere wishes,
MY

**Comment by zikai1** [comment]
The following presents some of my 2D stitching results:
![575ae6fe2c0a1fb20328e1a37df5ad9](https://user-images.githubusercontent.com/37583980/227072797-e49bf67f-6bb2-407b-b923-54090a8fd04e.png)
![861b19f0e3a0847a250c22bcf1e4673](https://user-images.githubusercontent.com/37583980/227072948-50073dee-2d32-427e-9149-db93760c486e.png)

Hi Russel Torres, it seems that the stitching is correct, but the visualization is errornous. Do I need to set or tune parameters? Which parameter should I set? 

Thank you again.

**Comment by RussTorres** [comment]
Hello,

My initial reaction to this is that the montage may be under-regularized and optimizing by producing a sheared representation of the tiles.  As the optimal regularization parameter lambda is dependent on a number of factors (principally the number and weight of point correspondences), you likely need to change this.  One sanity check on what a minimally deformed montage should ideally look like is to solve for a TranslationModel, which should produce a translation-only montage that looks like optimal stage coordinates.

This translation model is what the solve is regularized against using the "translation_factor" variable (which describes the relation of the translation to the higher order transformation in the solve), so tweaking the value of that or lambda will vary how deformed your montage can be in service of bringing correspondences closer together.

In the elife paper we described a method of exploring the tradeoff of some of these parameters.  I am not sure if this figure made it in (was originally supposed to be a supplement), but it describes some of the effects of regularization on the section rendering.  note that the "individual tile" part of this is actually describing the corner overlap of multiple tiles, hence why you see a seam.

![image](https://user-images.githubusercontent.com/7576514/227606088-07ab0911-75a5-43ce-a5aa-461d889065c0.png)


I have raised https://github.com/AllenInstitute/asap-modules/issues/250 describing the addition of automated parameter search to the main repos.


If you believe this is a rendering error, however, it would be good to understand why -- can you share some example tilespecs (in json form) so it's possible to visualize the stitching result?

Thanks,
Russel

**Comment by zikai1** [comment]
Hi @RussTorres 
Thanks for your timely response. Thank you.

I will change the following parameters in `solve.py` to re-stitch the tiles:
![69234a7af7745201846ff7c2d291731](https://user-images.githubusercontent.com/37583980/227816399-661d9f03-d692-43b7-b8c9-854c0c464e8e.png)
Since I used the default parameters to solve the tilespecs before.


The tilespecs produced by me can be downloaded from [https://drive.google.com/file/d/1L7sROWEliXa5nLOPj7KerjBA2zjFLSS-/view?usp=share_link](url)
These tilespecs were from your shared file `21617_R1_166_T5_15_20201231140731_20201231140731` and they constitute a section, i.e., z=0.

Thank you to further provide the file regarding the automated parameter searching. I am looking forward to seeing that. Thank you.

Best and sincere wishes,
MY

**Comment by zikai1** [comment]
Hi RussTorres,

After change the `regularization` parameter in `solve.py` to the following:

```
"regularization": {
        "default_lambda": 1.0e7,#1.0e3 in default
        "translation_factor": 1.0e-2#1.0e-5 in default
    },
```  
I attain resonable 2D stitching results with images from `21617_R1_166_T5_15_20201231140731_20201231140731`. However, when I use the same set of parameters in my own images, the stitching result is
![bdf5c4422df3d0f9fb6e21b5a363568](https://user-images.githubusercontent.com/37583980/227878524-85bf3ab9-01c3-473b-97a4-069e28724d15.png)
Then I further increase `regularization` and it produces
![1 0_2](https://user-images.githubusercontent.com/37583980/227878821-c5f5197f-b77e-4414-a674-da34a48bd197.jpg)
and 
![1 0_1](https://user-images.githubusercontent.com/37583980/227879338-6775221e-356c-4de2-a2df-bc3502d986d7.jpg)
It seems that the regularization effect is too heavy. I further tune several sets of parameters but the results seem unchanged.

The tiles I used indeed have about 50% overlappings as indicated by the red and green lines:
![1 0_1](https://user-images.githubusercontent.com/37583980/227881496-c32eb2ca-9ef8-4ea7-9dc1-51f5c45e1f26.jpg)

In each section, there are 9 tiles as shown up. Besides, the other parameters used in `solve.py ` is in the default format, as shown below:
![21c2e7488353d7c0fb6b67d14b35904](https://user-images.githubusercontent.com/37583980/227885435-c3400a7f-b56d-44e7-b3fb-ccd9a61ba598.png)


Hi RussTorres, could you help me stitch the above 9 tiles? You can easily download them from [https://drive.google.com/drive/folders/19Wg4sVyw3v9-2z_b9LjCbzjVOTvAjdj-?usp=share_link](url)
and then I will know where my settings are incorrect and how to set them. 


Thank for your help, Dr. RussTorres.

Thanks,
MY

**Comment by zikai1** [comment]
Hi Dr. Russ Torres,
Based on your suggestions, I have stitched tiles together. Thank you very much!

The key changes I did were increasing the values of `"regularization"` in `solve.py` file and relocated my images to make it customize the `metadata.json` file you provided.
