### ISSUE TITLE
When loading matches from file, matches are collected based on intersection not equality

### ISSUE THREAD

**Issue by mlnichols** [AllenInstitute/BigFeta#6]
In ```utils.py```

```
def get_matches(iId, jId, collection, dbconnection): .

    ... [Removed deliberately]

    matches = []
    if collection['db_interface'] == 'file':
        matches = jsongz.load(collection['input_file'])
        matches = [m for m in matches
                   if set([m['pGroupId'], m['qGroupId']]) & set([iId, jId])]
```

Here we'll return all matches that have one of  'pGroupId', 'qGroupId' in common with  'iId', 'jId'.

It seems to me this behaviour is wrong (let me know if I'm mistaken). It is filtered out at the next step in bigfeta.py but should still rely on equality here.

As a sub-example

pGroupId = '1.0'
qGroupId = '2.0'
(i.e. the match is between layer 1 and layer 2)

iId = '2.0'
jId = '3.0'
We want the sections between 2 and 3

```set([pGroupId, qGroupId]) & set([iId, jId])``` evaluates to a set of '2.0' (the intersection of them) and if then evaluates to True since the set isn't empty.

It may be that you wanted to have the set elements be lists, but lists are unhashable. You could have the elements be tuples (but shouldn't since the order then matters which while in practice it is ordered, it isn't guaranteed from what I understand) in which case:

```set([(pGroupId, qGroupId)]) & set([(iId, jId)])``` evaluates correctly (or ```set(((pGroupId, qGroupId))) & set(((iId, jId)))``` but not ```set((pGroupId, qGroupId)) & set((iId, jId))``` since it collapses the iterates over the tuple or list to create the set).

Assuming you wanted it to include them only if they match the section id's then there's a few different ways to get it to work.

The smallest change is to just use set equality, i.e.

```matches = [m for m in matches if set([m['pGroupId'], m['qGroupId']]) == set([iId, jId])]```

This requires a lot of set generations if the matches is large, which is a little silly (but shouldn't take much time, so if it's conceptually neater it's fine), so I'd probably suggest the following.

```
def get_matches(iId, jId, collection, dbconnection): .

    ... [Removed deliberately]

    matches = []
    if collection['db_interface'] == 'file':
        matches = jsongz.load(collection['input_file']) #As a side note this should be cached, or the code refactored to only load once but not relevant to this bug report
        section_set = set([iId, jId])
        matches = [m for m in matches
                   if m['pGroupId'] in section_set and m['qGroupId'] in section_set]
```

**Comment by djkapner** [comment]
resolved in PR  https://github.com/AllenInstitute/BigFeta/pull/7
