### ISSUE TITLE
Very rough 3D alignment

### ISSUE THREAD

**Issue by lanery** [AllenInstitute/BigFeta#8]
Hello,

I am having a great deal of difficulty aligning my EM image stack with `BigFeta`. I'm hoping you guys could provide some guidance in where I might be going wrong. Apologies in advance if this issue would be more appropriate elsewhere.

#### Some context
I have a fairly small (9 layers / ~320 EM tiles per layer / ~3000 total tiles) stack of EM data that I aligned with `EM_aligner_python`---what I gather is the predecessor to `BigFeta`. The montage went quite well I would say (at least visually -- images below). As I typically just have one section, this is the first time I've tried a 3D alignment of my data. When things started to go haywire with `EM_aligner_python`, I hoped updating to `BigFeta` would fix up the alignment, but alas.

Here is the 3rd and 4th z layer of the montaged stack
![montaged](https://user-images.githubusercontent.com/8359342/70641507-0a9f8d00-1c3e-11ea-861e-9c3c4dba417d.png)

And then after running the alignment with bigfeta the result is
![aligned](https://user-images.githubusercontent.com/8359342/70641885-97e2e180-1c3e-11ea-91ad-ff0b0023075a.png)

#### Attempts at troubleshooting
I've tried sweeping through the regularization parameters `default_lambda` and `translation_factor` by several orders of magnitude (somewhat aimlessly just to see what would happen). While the resulting alignment indeed changes, I've not found an alignment much better than that shown above.

#### Details
To run `bigfeta` I make a call to
```
python -m bigfeta.bigfeta --input_json /path/to/align.json
```

where my `input_json` looks like
```json
{
  "first_section": 1.0,
  "last_section": 9.0,
  "solve_type": "3D",
  "close_stack": "True",
  "transformation": "affine",
  "start_from_file": "",
  "output_mode": "stack",
  "input_stack": {
    "owner": "rlane",
    "project": "20191101_RL010",
    "name": "lil_EM_montaged",
    "host": "sonic",
    "port": 8080,
    "mongo_host": "sonic",
    "mongo_port": 27017,
    "client_scripts": "/home/catmaid/render/render-ws-java-client/src/main/scripts",
    "collection_type": "stack",
    "db_interface": "mongo"
  },
  "pointmatch": {
    "owner": "rlane",
    "name": "20191101_RL010_lil_EM_montaged_points",
    "host": "sonic",
    "port": 8080,
    "mongo_host": "sonic",
    "mongo_port": 27017,
    "client_scripts": "/home/catmaid/render/render-ws-java-client/src/main/scripts",
    "collection_type": "pointmatch",
    "db_interface": "mongo"
  },
  "output_stack": {
    "owner": "rlane",
    "project": "20191101_RL010",
    "name": "lil_EM_aligned",
    "host": "sonic",
    "port": 8080,
    "mongo_host": "sonic",
    "mongo_port": 27017,
    "client_scripts": "/home/catmaid/render/render-ws-java-client/src/main/scripts",
    "collection_type": "stack",
    "db_interface": "render"
  },
  "hdf5_options": {
    "output_dir": "",
    "chunks_per_file": -1
  },
  "matrix_assembly": {
    "depth": 2,
    "montage_pt_weight": 1.0,
    "cross_pt_weight": 0.1,
    "npts_min": 5,
    "npts_max": 500,
    "inverse_dz": "True"
  },
  "regularization": {
    "default_lambda": 1000,
    "translation_factor": 0.05
  }
}
```

**Comment by djkapner** [comment]
Hi Ryan,
A first good sanity check is if you crank the regularization parameters way up, to 1e10 or something, it should be so constrained as to return to you the same alignment as the output. Then you can ease them down.
Another way I've had success with this kind of 3D rough alignment is to start with rigid and then proceed to affine. In BigFeta's case, this is a 3-step process. The transformation would be RotationModel, followed by TranslationModel, followed by AffineModel. If your tiles are way off to start with, this can help decouple shear and scale from rotation.
Let me know if either of these insights helps.
Dan

**Comment by RussTorres** [comment]
We have also had success with building and matching tilespecs which represent the whole montage (in our case, using a downsampled rendering) and using BigFeta's nonlinear solves on those.  This is nice for us because it preserves montage quality and gives us easily accessible overviews.  render-modules (link below) has our solution to applying the transformations from these downsampled 3d stacks to the montage stack.

https://github.com/AllenInstitute/render-modules/blob/master/rendermodules/rough_align/apply_rough_alignment_to_montages.py

**Comment by lanery** [comment]
Thank you both for your feedback -- sorry it took so long for me to return to this! Both of your comments were helpful, but in the end I believe my mistake was having different match collections for the 2D vs 3D alignment. So when I ran the 3D alignment it was completely ignoring the 2D montages.
